name: Shy Boyz
markdown: redcarpet
pygments: true
permalink: /:categories/:title
baseurl: "http://samargulies.github.io/shy-boyz/"

exclude:
  - .gitignore
  - README.md

# Prose settings
prose:
  media: "assets/img"
  rooturl: "_posts"
  siteurl: "http://samargulies.github.io/shy-boyz/"