name: Shy Boyz
markdown: redcarpet
pygments: true
permalink: /:categories/:title
baseurl: "http://shyboyz.net"

exclude:
  - .gitignore
  - README.md
 
# Localized Phrases
translations:
  en:
    news: "News"
    footer-text: "&copy; MMXIII Shy Way Entertainment"
    site-description: "The official website of the <em>Shy Boyz</em>: the greatest band in the world."
  bg:
    news: "Новини"
    footer-text: "&copy; MMXIII Shy Way забавление"
    site-description: "Официалният уебсайт на <em>Shy Boyz</em>: най-голямата група в света."

# Prose settings
prose:
  media: "assets/img"
  rooturl: "_posts"
  siteurl: "http://shyboyz.net"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "lang"
        field:
          element: "select"
          label: "Select language"
          placeholder: "English"
          options: 
            - name: 'English'
              value: 'en'
            - name: 'Bulgarian'
              value: 'bg'
          selected: "en"
      - name: "layout"
        field:
          element: "select"
          label: "Select a layout"
          placeholder: "Default"
          options:
            - name: "Post"
              value: "post"
          selected: "post"
    _posts/en:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "lang"
        field:
          element: "select"
          label: "Select language"
          placeholder: "English"
          options: 
            - name: 'English'
              value: 'en'
            - name: 'Bulgarian'
              value: 'bg'
          selected: "en"
      - name: "layout"
        field:
          element: "select"
          label: "Select a layout"
          placeholder: "Default"
          options:
            - name: "Post"
              value: "post"
          selected: "post"
      - name: "categories"
        field:
          element: "hidden"
          value:
            - "en"